[package]
name = "ethereum-trading-mcp"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "1.0.9", features = ["full"] }
rmcp = { version = "0.9.1", features = ["server"] }
tokio = { version = "1.48.0", features = ["full"] }
tracing = "0.1.43"
tracing-subscriber = "0.3.22"
